### ISSUE TITLE
Getting started for iOS?

### ISSUE THREAD

**Issue by schott12521** [TheArchitect123/KmpEssentials#1]
I love this project, but I want to know how to setup for iOS -- do you have any examples? I could write some of the documentation if you already have a working example.

**Comment by TheArchitect123** [comment]
Hi, Thanks for the feedback.
For iOS, you don't need to do any setup.

Simply import the project into your shared build.gradle file.

`implementation("io.github.thearchitect123:kmpEssentials:0.8.2") // latest package`

Then you can start using the api in your shared module. 
(You can find a list of modules available here) [https://github.com/TheArchitect123/KmpEssentials/blob/main/README.md#below-is-a-list-of-all-modules-along-with-what-each-of-them-do]

Android however requires initialisation inside your Activity's **onCreate** method, that's because the context needs to be passed, but iOS initialises automatically.

**Comment by schott12521** [comment]
I appreciate the response, let me know if you're looking for collaborators.

**Comment by TheArchitect123** [comment]
@schott12521 
**You can find the documentation site available here.**

https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/
