### ISSUE TITLE
Error while sharing a file

### ISSUE THREAD

**Issue by Monabr** [TheArchitect123/KmpEssentials#7]
`android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`

Hi. Please fix this.

**Comment by TheArchitect123** [comment]
Yeah, that's because I'm using the ApplicationContext instead of ActivityContext.
I'll push a new version soon that fixes this.

**Comment by TheArchitect123** [comment]
I'm pushing version 1.0.5.
Should be ready to download in 15 minutes.

Please try again after it's ready

**Comment by TheArchitect123** [comment]
**Try version 1.0.5.** This should fix it.
`implementation("io.github.thearchitect123:kmpEssentials:1.0.5")`

I switched to using an ActivityContext, so the IntentChooser is managed by the activity now, not by the Application.
Since it's really the same user experience there's no need to have the ApplicationContext manage this api.

**Comment by TheArchitect123** [comment]
Since you have some other flags as well (on your code snippet above), I'll add another Api which allows you to pass in extra flags into the intent. Beyond just the default ones provided under the hood.

This will you allow to customise the intent choose + any permissions it needs from the device.

**Comment by TheArchitect123** [comment]
**In regards to your first question:** 
If we're talking about the KmpShare api, the intents are scoped to the function itself. So once the function closes all the objects related are picked up by the garbage collector.

If you're asking about the ApplicationContext + ActivityContext, these need to be static objects inside the library.
The activityContext gets reset everytime the Activity changes on your app's lifecycle **OnCreate.**

Which is why in the documentation I mention to add the KmpInitialise function in **OnCreate** so the app resets the activityContext whenever it needs to.

https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/#setup-for-android

**Comment by TheArchitect123** [comment]
**In regards your second question**, I'll add another Api so you can customise the intent chooser. So the filename will be properly configured.

**Comment by TheArchitect123** [comment]
I think as well in general it is better to have the applicationContext as much as possible. 
Yeah I'll think about that. And thanks for the tip

> @TheArchitect123 Seems like 1.0.5 resolves the issue but I have 2 more questions:
> 
> 1. I am using this api from ViewModel. Are you sure there will be no memory leaks?
> 2. We need to set type of shared file. Without it a file got sent like `File_name` instead of `File_name.csv`

**Comment by TheArchitect123** [comment]
I've also replaced the Share Api to use ApplicationContext now.
So the ActivityContext is never used. 

And ApplicationContext is kept in memory by the device anyway. So this should resolve concerns of memory leaks
